spring:
  datasource:
    url: jdbc:mysql://localhost:3307/gmall_pms
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  redis:
    database: 0
    port: 6379
    host: 192.168.1.3
  elasticsearch:
    jest:
      uris: http://192.168.1.3:9200,http://192.168.1.3:9201,http://192.168.1.3:9202
      read-timeout: 20000 #读取超时
      connection-timeout: 20000 #连接超时
dubbo:
  application:
    name: gmall-pms
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
  consumer:
    check: false

mybatis-plus:
  mapper-locations: classpath:xml/*.xml

